2018-12-12 16:50:49,256 [3] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 16:50:49,261 [3] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 16:56:20,257 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-12 16:56:22,222 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-12 16:56:22,234 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-12 16:56:36,945 [7] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:b8513e48-21ad-4925-928a-f598428d056e
Error Number:4060,State:1,Class:11
2018-12-12 16:56:36,945 [12] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:b8513e48-21ad-4925-928a-f598428d056e
Error Number:4060,State:1,Class:11
2018-12-12 16:56:36,945 [10] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:b8513e48-21ad-4925-928a-f598428d056e
Error Number:4060,State:1,Class:11
2018-12-12 17:01:22,249 [9] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 17:01:22,250 [9] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 17:12:12,179 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-12 17:12:15,055 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-12 17:12:15,068 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-12 17:12:28,702 [5] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:7698e594-a394-45da-b8a4-0d821d118359
Error Number:4060,State:1,Class:11
2018-12-12 17:12:28,702 [10] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:7698e594-a394-45da-b8a4-0d821d118359
Error Number:4060,State:1,Class:11
2018-12-12 17:12:28,702 [8] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:7698e594-a394-45da-b8a4-0d821d118359
Error Number:4060,State:1,Class:11
2018-12-12 17:12:28,702 [4] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:7698e594-a394-45da-b8a4-0d821d118359
Error Number:4060,State:1,Class:11
2018-12-12 17:12:28,703 [11] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:7698e594-a394-45da-b8a4-0d821d118359
Error Number:4060,State:1,Class:11
2018-12-12 17:17:15,080 [18] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 17:17:15,081 [18] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 17:22:15,081 [26] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 17:22:15,081 [26] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 17:24:53,812 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-12 17:24:55,679 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-12 17:24:55,706 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-12 17:26:23,550 [20] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:6e32ac54-1889-466b-a4fd-a24d254c5d3e
Error Number:4060,State:1,Class:11
2018-12-12 17:26:23,550 [11] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:6e32ac54-1889-466b-a4fd-a24d254c5d3e
Error Number:4060,State:1,Class:11
2018-12-12 17:26:23,550 [6] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:6e32ac54-1889-466b-a4fd-a24d254c5d3e
Error Number:4060,State:1,Class:11
2018-12-12 17:29:55,715 [3] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 17:29:55,716 [3] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 17:34:05,283 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-12 17:34:07,145 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-12 17:34:07,161 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-12 17:34:26,339 [4] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:2d08551d-0a1f-4f00-8032-61b4a57cd72e
Error Number:4060,State:1,Class:11
2018-12-12 17:34:26,339 [9] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:2d08551d-0a1f-4f00-8032-61b4a57cd72e
Error Number:4060,State:1,Class:11
2018-12-12 17:34:26,339 [5] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:2d08551d-0a1f-4f00-8032-61b4a57cd72e
Error Number:4060,State:1,Class:11
2018-12-12 17:39:07,174 [25] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 17:39:07,175 [25] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 18:25:33,308 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-12 18:25:34,911 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-12 18:25:34,921 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-12 18:25:51,572 [11] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:444e5333-cbea-4fb0-8711-010aecfc86cc
Error Number:4060,State:1,Class:11
2018-12-12 18:25:51,572 [9] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:444e5333-cbea-4fb0-8711-010aecfc86cc
Error Number:4060,State:1,Class:11
2018-12-12 18:25:51,572 [5] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:444e5333-cbea-4fb0-8711-010aecfc86cc
Error Number:4060,State:1,Class:11
2018-12-12 18:30:34,938 [12] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 18:30:34,939 [12] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 18:35:34,950 [34] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 18:35:34,951 [34] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 18:36:20,310 [3] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:49e5fa37-dd28-4b59-8a60-e35f22c846ea
Error Number:4060,State:1,Class:11
2018-12-12 18:36:20,310 [33] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:49e5fa37-dd28-4b59-8a60-e35f22c846ea
Error Number:4060,State:1,Class:11
2018-12-12 18:40:34,951 [31] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 18:40:34,951 [31] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 18:45:34,953 [33] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 18:45:34,953 [33] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 18:50:34,955 [16] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 18:50:34,955 [16] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 18:55:34,971 [25] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 18:55:34,971 [25] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 19:00:34,981 [28] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 19:00:34,982 [28] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 19:05:34,982 [22] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 19:05:34,982 [22] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-12 19:10:34,983 [21] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-12 19:10:34,983 [21] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 12:31:35,397 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-13 12:31:37,334 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 12:31:37,350 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-13 12:33:21,851 [9] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:1f0eaca3-19fe-40fa-9810-aa1e804989dd
Error Number:4060,State:1,Class:11
2018-12-13 12:33:21,851 [13] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:1f0eaca3-19fe-40fa-9810-aa1e804989dd
Error Number:4060,State:1,Class:11
2018-12-13 12:33:21,851 [19] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:1f0eaca3-19fe-40fa-9810-aa1e804989dd
Error Number:4060,State:1,Class:11
2018-12-13 12:33:22,010 [22] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:1f0eaca3-19fe-40fa-9810-aa1e804989dd
Error Number:4060,State:1,Class:11
2018-12-13 12:33:22,023 [9] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:1f0eaca3-19fe-40fa-9810-aa1e804989dd
Error Number:4060,State:1,Class:11
2018-12-13 12:33:22,220 [9] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:1f0eaca3-19fe-40fa-9810-aa1e804989dd
Error Number:4060,State:1,Class:11
2018-12-13 12:36:37,367 [21] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 12:36:37,369 [21] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 12:41:37,370 [11] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 12:41:37,370 [11] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 12:48:54,795 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-13 12:48:56,890 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 12:48:56,912 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-13 12:49:16,777 [4] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:d65aa130-542e-47dd-b2ac-a1dc300196d7
Error Number:4060,State:1,Class:11
2018-12-13 12:49:16,777 [7] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:d65aa130-542e-47dd-b2ac-a1dc300196d7
Error Number:4060,State:1,Class:11
2018-12-13 12:49:16,777 [12] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:d65aa130-542e-47dd-b2ac-a1dc300196d7
Error Number:4060,State:1,Class:11
2018-12-13 12:49:16,777 [5] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:d65aa130-542e-47dd-b2ac-a1dc300196d7
Error Number:4060,State:1,Class:11
2018-12-13 12:53:56,913 [25] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 12:53:56,914 [25] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 13:11:09,525 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-13 13:11:11,537 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 13:11:11,552 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-13 13:16:11,555 [7] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 13:16:11,556 [7] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 13:21:11,568 [3] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 13:21:11,568 [3] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 13:26:11,570 [5] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 13:26:11,570 [5] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 13:29:35,382 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-13 13:29:36,258 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:29:37,165 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 13:29:37,183 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-13 13:29:55,622 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:29:55,625 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 13:33:34,499 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:33:34,501 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 13:34:37,184 [20] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 13:34:37,185 [20] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 13:34:40,063 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:34:40,064 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 08/16/2018 00:00:00
2018-12-13 13:36:43,117 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:36:43,169 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not validate xml signature of:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>LLVa1QGzWCdb87dfAI8uR+AdAis=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>EoQJT4dLx7Fo+8jlffcYikskA7k1vrOg5Mjx6tVf9i1U63wxCs/krt7ZinKLeA9drbQKdPjhnsE+rLYtMB3N2vpShPR9e2U0NgXidosDzE7QzYCsyICT8/l+CH4JW0fjWX/sY4VDDysbWLR5iq4hVSlRPfc0W+roHGfNXzuOAV8=</SignatureValue>
  </Signature>
</license>
2018-12-13 13:36:43,170 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Failed validating license:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>LLVa1QGzWCdb87dfAI8uR+AdAis=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>EoQJT4dLx7Fo+8jlffcYikskA7k1vrOg5Mjx6tVf9i1U63wxCs/krt7ZinKLeA9drbQKdPjhnsE+rLYtMB3N2vpShPR9e2U0NgXidosDzE7QzYCsyICT8/l+CH4JW0fjWX/sY4VDDysbWLR5iq4hVSlRPfc0W+roHGfNXzuOAV8=</SignatureValue>
  </Signature>
</license>
2018-12-13 13:36:43,170 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not validate existing license
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>LLVa1QGzWCdb87dfAI8uR+AdAis=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>EoQJT4dLx7Fo+8jlffcYikskA7k1vrOg5Mjx6tVf9i1U63wxCs/krt7ZinKLeA9drbQKdPjhnsE+rLYtMB3N2vpShPR9e2U0NgXidosDzE7QzYCsyICT8/l+CH4JW0fjWX/sY4VDDysbWLR5iq4hVSlRPfc0W+roHGfNXzuOAV8=</SignatureValue>
  </Signature>
</license>
2018-12-13 13:39:37,184 [12] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 13:39:37,185 [12] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 13:40:58,430 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:40:58,432 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not validate xml signature of:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" FloatingLicenseExpiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>LLVa1QGzWCdb87dfAI8uR+AdAis=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>EoQJT4dLx7Fo+8jlffcYikskA7k1vrOg5Mjx6tVf9i1U63wxCs/krt7ZinKLeA9drbQKdPjhnsE+rLYtMB3N2vpShPR9e2U0NgXidosDzE7QzYCsyICT8/l+CH4JW0fjWX/sY4VDDysbWLR5iq4hVSlRPfc0W+roHGfNXzuOAV8=</SignatureValue>
  </Signature>
</license>
2018-12-13 13:40:58,432 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Failed validating license:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" FloatingLicenseExpiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>LLVa1QGzWCdb87dfAI8uR+AdAis=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>EoQJT4dLx7Fo+8jlffcYikskA7k1vrOg5Mjx6tVf9i1U63wxCs/krt7ZinKLeA9drbQKdPjhnsE+rLYtMB3N2vpShPR9e2U0NgXidosDzE7QzYCsyICT8/l+CH4JW0fjWX/sY4VDDysbWLR5iq4hVSlRPfc0W+roHGfNXzuOAV8=</SignatureValue>
  </Signature>
</license>
2018-12-13 13:40:58,433 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not validate existing license
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" FloatingLicenseExpiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>LLVa1QGzWCdb87dfAI8uR+AdAis=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>EoQJT4dLx7Fo+8jlffcYikskA7k1vrOg5Mjx6tVf9i1U63wxCs/krt7ZinKLeA9drbQKdPjhnsE+rLYtMB3N2vpShPR9e2U0NgXidosDzE7QzYCsyICT8/l+CH4JW0fjWX/sY4VDDysbWLR5iq4hVSlRPfc0W+roHGfNXzuOAV8=</SignatureValue>
  </Signature>
</license>
2018-12-13 13:43:43,117 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 13:43:43,118 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not find this signature node on license:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
</license>
2018-12-13 13:43:43,119 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not validate xml signature of:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
</license>
2018-12-13 13:43:43,119 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Failed validating license:
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
</license>
2018-12-13 13:43:43,120 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - Could not validate existing license
<?xml version="1.0" encoding="utf-8"?>
<license id="f74d43ce-7280-4133-84fa-43be02688667" expiration="2218-11-24T10:03:35.6237903" type="Trial" prof="efprof" version="5" updatesExpiration="2218-Nov-24">
  <name>522504447</name>
</license>
2018-12-13 13:44:37,193 [17] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 13:44:37,193 [17] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Got invalidation notification TimeExpired
2018-12-13 14:35:44,365 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-13 14:35:45,208 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-13 14:35:46,077 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-13 14:35:46,090 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-13 14:40:04,755 [8] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:4e54cce8-83c6-430d-a8b9-46b7b30af27a
Error Number:4060,State:1,Class:11
2018-12-13 14:40:04,755 [12] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:4e54cce8-83c6-430d-a8b9-46b7b30af27a
Error Number:4060,State:1,Class:11
2018-12-13 14:40:04,755 [17] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:4e54cce8-83c6-430d-a8b9-46b7b30af27a
Error Number:4060,State:1,Class:11
2018-12-13 14:40:04,756 [6] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:4e54cce8-83c6-430d-a8b9-46b7b30af27a
Error Number:4060,State:1,Class:11
2018-12-13 14:40:04,756 [13] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:4e54cce8-83c6-430d-a8b9-46b7b30af27a
Error Number:4060,State:1,Class:11
2018-12-13 14:40:04,756 [9] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:4e54cce8-83c6-430d-a8b9-46b7b30af27a
Error Number:4060,State:1,Class:11
2018-12-13 14:40:46,103 [9] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 14:45:46,116 [20] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 14:50:46,119 [26] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 14:55:46,119 [6] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:00:46,121 [9] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:05:46,121 [8] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:10:46,123 [20] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:15:46,133 [22] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:20:46,135 [8] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:25:46,136 [23] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:30:46,138 [6] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:35:46,140 [21] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:40:46,153 [22] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:45:46,156 [12] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:50:46,161 [12] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-13 15:55:46,162 [19] ERROR Rhino.Licensing.AbstractLicenseValidator [(null)] - The license have expired and can no longer be used
2018-12-14 10:56:48,007 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-14 10:56:48,736 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-14 10:56:49,478 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-14 10:56:49,491 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-14 11:08:55,822 [1] DEBUG HibernatingRhinos.Profiler.Client.App [(null)] - Profiler initialized. Build: 4041
2018-12-14 11:08:56,565 [1] INFO  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Using floating license server: http://localhost:12603/NHProfLicenseServer.svc
2018-12-14 11:08:57,349 [1] WARN  Rhino.Licensing.AbstractLicenseValidator [(null)] - License expiration date is 11/24/2018 10:03:35
2018-12-14 11:08:57,376 [1] WARN  HibernatingRhinos.Profiler.Client.Licensing.LicensePromptModel [(null)] - Second chance license validation has failed
Rhino.Licensing.LicenseExpiredException: Expiration Date: 2018/11/24 10:03:35
   在 Rhino.Licensing.AbstractLicenseValidator.IsLicenseValid()
   在 Rhino.Licensing.AbstractLicenseValidator.AssertValidLicense(Action onValidLicense)
   在 HibernatingRhinos.Profiler.Client.Services.ProfilerLicenseValidator.AssertValidLicense()
   在 HibernatingRhinos.Profiler.Client.Licensing.LicenseInformationModel.ConfirmLicense(Boolean showDialogIfLicenseDoesNotExists)
2018-12-14 11:11:49,849 [13] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:fa0bcb8b-514e-4380-95c8-cb0dc53247da
Error Number:4060,State:1,Class:11
2018-12-14 11:11:49,849 [10] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:fa0bcb8b-514e-4380-95c8-cb0dc53247da
Error Number:4060,State:1,Class:11
2018-12-14 11:11:49,849 [7] ERROR HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache [(null)] - Could not open connection
System.Data.SqlClient.SqlException (0x80131904): 无法打开登录所请求的数据库 "Tztech_Next_20180211"。登录失败。
用户 'sa' 登录失败。
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 HibernatingRhinos.Profiler.BackEnd.Infrastructure.SchemaCache.TaskHelper(String tableName, ConnectionInfo connection)
ClientConnectionId:fa0bcb8b-514e-4380-95c8-cb0dc53247da
Error Number:4060,State:1,Class:11
